### ISSUE TITLE
How to use a different routing library?

### ISSUE THREAD

**Issue by alok87** [bxcodec/go-clean-arch#17]
If I want to replace `labstack/echo` in this implementation with https://github.com/go-chi/chi
Where to put the code and make the change?
Don't see any interface around delivery and middlewares.

**Comment by bxcodec** [comment]
Hi @alok87,
For my case, I will only change the delivery layer, if it too different with echo, well, it doesn't matter to change the implemetation of the entire of delivery layer, because it's just will change the delivery layer, not the entire projects. 

Currently, I don't see any important reasons to use the  interface here, but if you have some ideas, I'll listen to it?

**Comment by alok87** [comment]
Good to have interfaces around the routing library as when the project would require a new routing library we can just write a new implementation for the new routing library and use it. No?

**Comment by bxcodec** [comment]
I'm afraid to say No. Usually, people use framework for the HTTP handler to ease the routing things. And we can't treat every framework same, some framework can be used with struct, some don't. So I'll keep it just as is, to keep it flexible :D
